apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: flask-git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/nageshredhat/pipeline-text.git
    - name: revision
      value: main
