apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-flask-app
spec:
  params:
    - name: image
      type: string
  steps:
    - name: deploy
      image: bitnami/kubectl
      script: |
        kubectl set image deployment/flask-app flask-app=$(params.image)
