apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-flask-app
spec:
  params:
    - name: image
      type: string
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/workspace/docker-source/Dockerfile
        - --context=/workspace/docker-source
        - --destination=$(params.image)
